{application,cldr_utils,
             [{optional_applications,[castore,certifi]},
              {applications,[kernel,stdlib,elixir,logger,inets,ssl,decimal,
                             castore,certifi]},
              {description,"Map, Calendar, Digits, Decimal, HTTP, Macro, Math, and String helpers for ex_cldr.\n"},
              {modules,['Elixir.Cldr.Code','Elixir.Cldr.Decimal',
                        'Elixir.Cldr.Digits','Elixir.Cldr.Enum',
                        'Elixir.Cldr.Helpers','Elixir.Cldr.Http',
                        'Elixir.Cldr.Macros','Elixir.Cldr.Map',
                        'Elixir.Cldr.Math','Elixir.Cldr.String',
                        'Elixir.Cldr.Utils']},
              {registered,[]},
              {vsn,"2.26.0"}]}.
